### ISSUE TITLE
Overlay behind image on Android

### ISSUE THREAD

**Issue by Jingo91** [alexbrillant/react-native-deck-swiper#126]
I have an image on my card and the problem is, the overlays (Like, Nope, Super Like, Meh) are behind the image of the card. 
This means, when swiping right,left,top or bottom the overlay will not appear. Only in the last millimeters, when the card lowers the opacity, the overlay is slightly visible. On iOS however, the overlay is on top of the image and is shown perfectly. 
How can i solve this?

**Comment by webraptor** [comment]
Of the top of my head there's some zIndex or something in your styles that causes this. Perhaps if you share your <swiper /> code and styles we could help.

**Comment by Palisand** [comment]
I was experiencing the same thing because I had rendered my cards with **`elevation`** on Android but did not include the style property in the overlay label `wrapper`. The solution is simply to add an elevation that is greater than or equal to the elevation of the card:

```javascript
<Swiper
  ...
  renderCard={(card) => <View style={{elevation: 5, ...}}>...</View>}
  overlayLabelWrapperStyle={{elevation: 5, ...}}
/>
```

@Jingo91 If this solves your problem, please close this issue.
