### ISSUE TITLE
Allow to set size on Swiper container

### ISSUE THREAD

**Issue by jjant** [alexbrillant/react-native-deck-swiper#14]
It is useful to be able to set a fixed width/height to the Swiper container, but the current API doesn't allow it.

I needed to have two swipers on the same screen, and couldn't get this, so I had to modify the package.

This can be simply achieved by changing the following on the Swiper render method:
```diff
      <View
        style={[
          styles.container,
          {
+           height: this.props.height,
+           width: this.props.width,
            backgroundColor: this.props.backgroundColor,
            marginTop: this.props.marginTop,
            marginBottom: this.props.marginBottom
          }
        ]}
      >
```

I would prefer to just allow users to throw in a `style` prop into the Swiper component, perhaps discarding those styles you wouldn't like to accept.

I can throw a PR in if you like.

PS: Awesome package, Alex!

**Comment by alexbrillant** [comment]
Thanks! @jjant I do like. If you want, you can make a pull request. Otherwise, I can push this to the new version. Just tell me what you prefer

**Comment by alexbrillant** [comment]
@jjant . Thanks for asking. The cards have to be absolutely positioned because of the animations. I know that would be useful, but it isn't that simple. 

With the current version, you need to use the **marginTop, and marginBottom** props to achieve your desired effect. This is the best way to build what you are looking for.

Feel free to submit a pull request if you have a better idea, but the solution you provided is invalid with the current implementation. 

For all these reasons, I am closing this issue.
